version: "3"
services:
    onedrive:
        image: driveone/onedrive:edge
        restart: unless-stopped
        # to emulate -it. Especially important when need to reauth
        stdin_open: true # docker run -i
        tty: true        # docker run -t
        environment:
              # standard output of `id -u`
            - ONEDRIVE_UID=1000
              # standard output of `id -g`
            - ONEDRIVE_GID=1000

              # exposing env vars on 
            - ONEDRIVE_DATA_DIR=${ONEDRIVE_DATA_DIR}
            - ONEDRIVE_VERBOSE=${ONEDRIVE_VERBOSE}
            - ONEDRIVE_RESYNC=${ONEDRIVE_RESYNC}
            - ONEDRIVE_REAUTH=${ONEDRIVE_REAUTH}
            - ONEDRIVE_LOGOUT=${ONEDRIVE_LOGOUT}
        env_file: 
            - .env
        volumes: 
            - onedrive_conf:/onedrive/conf
              # should pull from .env file...or if not the "environment" mapping above (!)
            - ${ONEDRIVE_DATA_DIR}:/onedrive/data

volumes:
    onedrive_conf: 
        driver: local
        driver_opts:
            o: bind
            type: none
            device: ./configs
